'use strict';
const API='https://zgpuuliqtrpdjerniyio.supabase.co/functions/v1/caya-price-api';
const TOKEN_KEY='caya_price_session_v1',ID_KEY='caya_price_remember_id';
const $=id=>document.getElementById(id);
let token='',user=null,release=null,originalHtml='',stage=null,stageSerial=0,loadSerial=0,heartbeat=null,expiry=null,publishing=false;
const storageGet=(s,k)=>{try{return s.getItem(k)||'';}catch{return '';}};
const storageSet=(s,k,v)=>{try{v?s.setItem(k,v):s.removeItem(k);}catch{}};
function message(id,text,error=false){$(id).textContent=text;$(id).classList.toggle('error',error);}
function busy(text){$('busyText').textContent=text||'';$('busyBar').hidden=!text;}
async function request(path,{method='GET',body,raw=false,timeout=60000}={}){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),timeout);try{const headers=token?{Authorization:'Bearer '+token}:{};if(body!==undefined)headers['Content-Type']=raw?'text/html;charset=utf-8':'application/json';const response=await fetch(API+'/'+path,{method,headers,body:body===undefined?undefined:raw?body:JSON.stringify(body),signal:ac.signal,cache:'no-store',credentials:'omit'});if(!response.ok){const data=await response.json().catch(()=>({}));const e=new Error(data.error||'連線失敗，請稍後重試。');e.status=response.status;throw e;}return raw&&method==='GET'?response.text():response.json();}catch(e){if(e.name==='AbortError')throw Error('連線逾時，請確認網路後按重新載入。');if(e instanceof TypeError)throw Error('暫時無法連線到登入服務，請確認網路。');throw e;}finally{clearTimeout(timer);}}
function clearSession(text=''){clearInterval(heartbeat);clearTimeout(expiry);loadSerial++;stageSerial++;stage=null;originalHtml='';token='';user=null;release=null;storageSet(sessionStorage,TOKEN_KEY,'');$('appFrame').srcdoc='';$('appFrame').hidden=true;$('appView').hidden=true;$('loginView').hidden=false;$('password').value='';busy('');for(const d of document.querySelectorAll('dialog[open]'))d.close();message('loginStatus',text);}
async function signOut(){try{await request('logout',{method:'POST',body:{},timeout:12000});}catch{}clearSession('已登出。');}
async function load(){if(!token)return;const serial=++loadSerial;stage=null;stageSerial++;$('loadError').hidden=true;$('appFrame').hidden=true;busy('載入你已提供的價格與促案…');try{const m=await request('me');if(serial!==loadSerial)return;user=m.user;release=m.release;$('userBadge').textContent=user.employee_id+' · '+(user.role==='admin'?'管理員':'同仁');for(const id of ['excelOpen','accountsOpen'])$(id).hidden=user.role!=='admin';if(!release)throw Error('網站正在整理已提供的資料，請稍後按重新載入，不必再上傳檔案。');$('releaseLabel').textContent=release.version+' · 登入後共用';originalHtml=await request('app',{raw:true,timeout:90000});if(serial!==loadSerial)return;const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(originalHtml))),x=>x.toString(16).padStart(2,'0')).join('');if(sha!==release.sha256)throw Error('檔案完整性核對未通過，請重新載入。');busy('建立本期查價索引，請稍候…');if(typeof window.cayaPrepareWorkspace!=='function')throw Error('商品篩選程式尚未載入，請關閉舊頁面後重新開啟網址。');$('appFrame').srcdoc=window.cayaPrepareWorkspace(originalHtml);$('appFrame').hidden=false;await new Promise((resolve,reject)=>{const start=Date.now(),timer=setInterval(()=>{if(serial!==loadSerial){clearInterval(timer);resolve();return;}try{const w=$('appFrame').contentWindow;if(w.__appError){clearInterval(timer);reject(Error(w.__appError));return;}if(w.__appReady){clearInterval(timer);w.cayaCloudSetRole?.(user.role);resolve();return;}}catch{}if(Date.now()-start>60000){clearInterval(timer);reject(Error('資料載入較久，請重新載入。'));}},160);});if(serial===loadSerial)$('connectionNote').hidden=true;}catch(e){if(serial!==loadSerial)return;if(e.status===401){clearSession(e.message);return;}$('appFrame').hidden=true;$('loadError').hidden=false;$('loadErrorText').textContent=e.message;}finally{if(serial===loadSerial)busy('');}}
async function enter(m){user=m.user;const remaining=new Date(m.expires_at).getTime()-Date.now();if(remaining<=0){clearSession('登入已到期，請重新登入。');return;}$('loginView').hidden=true;$('appView').hidden=false;clearTimeout(expiry);clearInterval(heartbeat);expiry=setTimeout(()=>clearSession('登入已到期，請重新登入。'),remaining);heartbeat=setInterval(async()=>{try{const m=await request('me',{timeout:20000});$('connectionNote').hidden=true;if(release&&m.release&&release.sha256!==m.release.sha256){$('connectionNote').hidden=false;$('connectionNote').textContent='已有新的共用版本，請按「重新載入」後再報價。';}}catch(e){if(e.status===401)clearSession(e.message);else{$('connectionNote').hidden=false;$('connectionNote').textContent='網路暫時不穩，請確認資料版本後再報價。';}}},90000);await load();}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginBtn').disabled=true;message('loginStatus','驗證登入中…');try{token='';const id=$('employee').value.trim(),m=await request('login',{method:'POST',body:{employee_id:id,password:$('password').value}});token=m.token;storageSet(sessionStorage,TOKEN_KEY,token);storageSet(localStorage,ID_KEY,$('remember').checked?id:'');$('password').value='';await enter(m);message('loginStatus','');}catch(e){message('loginStatus',e.message,true);}finally{$('loginBtn').disabled=false;}};
$('showPassword').onclick=()=>{const show=$('password').type==='password';$('password').type=show?'text':'password';$('showPassword').textContent=show?'隱藏':'顯示';};
$('logoutBtn').onclick=signOut;$('reloadBtn').onclick=load;$('retryBtn').onclick=load;
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>{if(publishing&&b.dataset.close==='excelDialog')return;$(b.dataset.close).close();};
function openExcel(){if(user?.role!=='admin')return;stage=null;stageSerial++;$('excelFile').value='';$('excelReview').hidden=true;$('dateWrap').hidden=true;$('publishExcel').disabled=true;message('excelStatus','');$('excelDialog').showModal();}
$('excelOpen').onclick=openExcel;window.addEventListener('message',e=>{if(e.source===$('appFrame').contentWindow&&e.origin===location.origin&&e.data?.type==='caya-open-excel')openExcel();});
$('excelFile').onchange=async()=>{const file=$('excelFile').files[0],serial=++stageSerial;stage=null;$('publishExcel').disabled=true;$('excelReview').hidden=true;$('dateWrap').hidden=true;if(!file)return;message('excelStatus','正在核對 Excel 頁籤與價格，尚未變更共用資料…');try{const w=$('appFrame').contentWindow;if(!w.__appReady||!w.cayaCloudStageExcel)throw Error('請先完成本期資料載入後再更新 Excel。');const staged=await w.cayaCloudStageExcel(file);if(serial!==stageSerial)return;stage=staged;const s=stage.summary;$('excelReview').textContent='檔案：'+s.filename+'\n'+s.sheets+' 個頁籤 · '+s.products.toLocaleString()+' 個料號\n'+s.numericPrices.toLocaleString()+' 筆數字專案價格'+(s.unrecognized?'\n注意：'+s.unrecognized+' 個頁籤未辨識，請先核對。':'');$('excelReview').hidden=false;$('dateWrap').hidden=false;$('excelDate').value=stage.version||'';$('publishExcel').disabled=false;message('excelStatus','Excel已讀取。請確認版本日期後發布；目前共用資料尚未改動。');}catch(e){if(serial===stageSerial)message('excelStatus',e.message,true);}};
$('excelDialog').addEventListener('close',()=>{if(!publishing){stageSerial++;stage=null;}});
function compose(snapshot){const doc=new DOMParser().parseFromString(originalHtml,'text/html');const seed=doc.getElementById('seed'),promos=doc.getElementById('promotionData');if(!seed||!promos)throw Error('工作台資料格式不正確。');seed.textContent=JSON.stringify(snapshot.seed).replace(/</g,'\\u003c');promos.textContent=JSON.stringify(snapshot.promotion).replace(/</g,'\\u003c');return '<!doctype html>\n'+doc.documentElement.outerHTML;}
$('publishExcel').onclick=async()=>{if(!stage||publishing)return;const version=$('excelDate').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(version)){message('excelStatus','請先確認價格版本日期。',true);return;}if(!confirm('確認發布 '+stage.summary.filename+'（'+version+'）給所有已開通同仁？促案日期不會跟著自動延長。'))return;publishing=true;$('publishExcel').disabled=true;$('excelFile').disabled=true;message('excelStatus','正在發布到私有共用空間，請勿關閉…');try{stage.seed.version=version;stage.version=version;const html=compose(stage);if(new TextEncoder().encode(html).length>12*1024*1024)throw Error('整份資料超過12MB，原共用版本不變。');await request('publish?version='+encodeURIComponent('CAYA 5.1 · '+version),{method:'POST',body:html,raw:true,timeout:120000});stage=null;$('excelDialog').close();await load();}catch(e){message('excelStatus',e.message+' 請重新載入確認目前共用版本。',true);}finally{publishing=false;$('excelFile').disabled=false;$('publishExcel').disabled=!stage;}};
$('passwordOpen').onclick=()=>{$('passwordForm').reset();message('passwordStatus','');$('passwordDialog').showModal();};$('passwordForm').onsubmit=async e=>{e.preventDefault();if($('newPw').value!==$('repeatPw').value){message('passwordStatus','兩次新密碼不一致。',true);return;}$('passwordSubmit').disabled=true;try{await request('password',{method:'POST',body:{current_password:$('oldPw').value,new_password:$('newPw').value}});$('passwordForm').reset();clearSession('密碼已修改，請使用新密碼重新登入。');}catch(e){message('passwordStatus',e.message,true);}finally{$('passwordSubmit').disabled=false;}};
async function listAccounts(){const result=await request('accounts');$('accountList').replaceChildren();for(const a of result.accounts){const row=document.createElement('div');row.className='account';const title=document.createElement('b');title.textContent=a.employee_id+(a.display_name?' · '+a.display_name:'');const detail=document.createElement('small');detail.textContent=(a.role==='admin'?'管理員':'同仁')+' · '+(a.active?'已啟用':'已停用');row.append(title,detail);if(a.role!=='admin'){const buttons=document.createElement('div');buttons.className='buttons';const fill=document.createElement('button');fill.textContent='填入重設表單';fill.onclick=()=>{$('accountId').value=a.employee_id;$('accountName').value=a.display_name||'';$('accountPw').focus();};const toggle=document.createElement('button');toggle.textContent=a.active?'停用':'啟用';toggle.onclick=async()=>{if(!confirm('確定'+(a.active?'停用':'啟用')+' '+a.employee_id+'？'))return;toggle.disabled=true;try{await request('account-status',{method:'POST',body:{employee_id:a.employee_id,active:!a.active}});await listAccounts();message('accountsStatus','帳號狀態已更新。');}catch(e){message('accountsStatus',e.message,true);toggle.disabled=false;}};buttons.append(fill,toggle);row.append(buttons);}$('accountList').append(row);}}
$('accountsOpen').onclick=async()=>{$('accountsDialog').showModal();message('accountsStatus','載入中…');try{await listAccounts();message('accountsStatus','');}catch(e){message('accountsStatus',e.message,true);}};
async function saveAccount(reset){if(!$('accountForm').reportValidity())return;if(reset&&!confirm('確定重設員編 '+$('accountId').value+' 的密碼？原登入會失效。'))return;['createAccount','resetAccount'].forEach(id=>$(id).disabled=true);try{await request(reset?'reset-password':'accounts',{method:'POST',body:{employee_id:$('accountId').value,display_name:$('accountName').value,password:$('accountPw').value}});$('accountPw').value='';await listAccounts();message('accountsStatus',reset?'密碼已重設。':'同仁帳號已開通。');}catch(e){message('accountsStatus',e.message,true);}finally{['createAccount','resetAccount'].forEach(id=>$(id).disabled=false);}}
$('accountForm').onsubmit=e=>{e.preventDefault();saveAccount(false);};$('resetAccount').onclick=()=>saveAccount(true);
(async()=>{const id=storageGet(localStorage,ID_KEY);if(/^\d{7}$/.test(id)){$('employee').value=id;$('remember').checked=true;}token=storageGet(sessionStorage,TOKEN_KEY);if(!token)return;message('loginStatus','恢復登入與載入本期資料…');try{await enter(await request('me'));message('loginStatus','');}catch{clearSession('請重新登入。');}})();
